variable "external_network_name" {}
variable "network_name" {}
variable "subnetwork_name" {}
variable "router_name" {}
variable "sec_group_name" {}
variable "secgroup_rule_name" {}
variable "port_ini" {}
variable "port_fin" {}
variable "server_name" {}
variable "flavor_name" {}
variable "key_name" {}
variable "user_data_file" {}
#variable "server2_name" {}
#variable "server3_name" {}
#variable "user_data2_file" {}
#variable "user_data3_file" {}